/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Language, LanguageCode, TranslationDictionary } from "./types";

export const SUPPORTED_LANGUAGES: Language[] = [
  { code: LanguageCode.EN, name: "English", flag: "🇺🇸", localName: "English" },
  { code: LanguageCode.ES, name: "Spanish", flag: "🇪🇸", localName: "Español" },
  { code: LanguageCode.HI, name: "Hindi", flag: "🇮🇳", localName: "हिन्दी" },
  { code: LanguageCode.PT, name: "Portuguese", flag: "🇵🇹", localName: "Português" },
  { code: LanguageCode.ZH, name: "Chinese", flag: "🇨🇳", localName: "中文" },
  { code: LanguageCode.FR, name: "French", flag: "🇫🇷", localName: "Français" },
];

export const STATIC_DICTIONARY: TranslationDictionary = {
  [LanguageCode.EN]: {
    metaTitle: "Global Portal",
    heroBadge: "Secure Multi-Language Hub",
    heroTitle: "Unlock Global Potential",
    heroSub: "Interact seamlessly with our global platform localized in your language of choice. Secure validation guards premium paths.",
    featuresTitle: "Enterprise Capabilities",
    featuresDesc: "Explore top features designed for robust multi-national operations and secure authorization systems.",
    serviceTitle: "Our Global Services",
    serviceDesc: "High-grade digital business units serving multiple languages with unified state persistence.",
    profileTitle: "Security Vault",
    profileDesc: "Review your secure credentials and language clearance status for verified access control.",
    
    // Home Cards
    analyticsCardTitle: "Global Analytics",
    analyticsCardDesc: "Real-time traffic aggregation representing over 140 countries with absolute synchronization.",
    marketCardTitle: "Neural Core Translate",
    marketCardDesc: "Leverage advanced Gemini server models below to dynamically translate any custom announcements.",
    supportCardTitle: "Secure Protocol",
    supportCardDesc: "Multi-factor OTP verification shields high-compliance locales including Francophone regions.",
    
    // Services
    service1Name: "Dynamic Localization API",
    service1Desc: "Instantly propagate dictionary states to distributed application frames across multiple regions.",
    service2Name: "Identity Verification Broker",
    service2Desc: "Authenticates users via standard tokenization before granting permission to localized settings.",
    service3Name: "Localized Assets Engine",
    service3Desc: "Serves tailored multimedia content, fonts, and numeric formats corresponding to native target preferences.",
    
    // Profile
    accountEmailLabel: "Registered Account Verification",
    registeredEmail: "",
    securityVerificationStatus: "Verification Privilege level",
    verifiedLabel: "Fully Verified (Clearance Active)",
    verificationRequiredLabel: "French OTP Check Required",
    languageLockDisclaimer: "Notice: The French language scope requires a one-time secure OTP check delivered to your email to validate locale-specific access guidelines.",
    
    // Navigation & General
    navHome: "Home Portal",
    navServices: "Services Hub",
    navSecurity: "Security Vault",
    changeLanguageBtn: "Change Language",
    generateOtpBtn: "Generate OTP Securely",
    sendingLabel: "Generating...",
    sentLabel: "Check Inbox",
    verifyAndApplyBtn: "Verify and Apply changes",
    enterOtpPlaceholder: "Enter 6-digit validation OTP",
    invalidOtpError: "Access Denied: The requested verification code is invalid or has expired.",
    otpVerifiedSuccess: "Success! French language permission has been cleanly authorized.",
    frenchLockedBadge: "Security Clearance Shielded",
    generalSuccess: "Website content translations applied successfully.",

    // New Localized Elements
    tabDashboard: "Dashboard",
    tabAssets: "Assets",
    tabPreferences: "Preferences",
    tabSecurity: "Security",
    langSettingsTitle: "Language Settings",
    langSettingsDesc: "Choose your preferred interface language. Changes apply globally across all modules.",
    securityVerificationTitle: "Security Verification",
    securityVerificationdesc: "Switching to French requires email validation for this region. Please verify your identity.",
    registeredEmailLabel: "Registered Email",
    generateOtpCodeBtn: "Generate OTP Code",
    generatingCodeLabel: "Generating code...",
    codeSentAlert: "A 6-digit verification code has been sent successfully!",
    verifyAndApplyLanguageBtn: "Verify & Apply Language",
    invalidOtpFormatError: "Please supply a valid 6-digit verification code.",
    authProxyOfflineError: "Auth proxy offline. Try again.",
    waitResendLabel: "Wait {time}s to resend code",
    readyResendLabel: "Ready to resend code",
    enterpriseDashboardTitle: "Enterprise Dashboard Overview",
    enterpriseDashboardDesc: "Explore premium visual metrics and integrated API statuses.",
    dynamicNeuralTitle: "Dynamic Neural Localizer (Powered by Gemini)",
    activeLocaleLabel: "ACTIVE LOCALE",
    translatorHintDesc: "Test the actual localization speed backed by Gemini 3.5 AI APIs: Type any material or phrases, and clicking translate will localise it to the current selected active language dictionary seamlessly.",
    sourceTextLabel: "Source copy (English)",
    textareaPlaceholderText: "Enter text to test localization...",
    translatedTargetLabel: "Translated Target",
    streamingConversionLabel: "Streaming dynamic neural conversion...",
    noConvertedOutputLabel: "No converted output yet. Enter text and run translator.",
    triggerDynamicTranslationBtn: "Trigger Dynamic Translation",
    exploreSpecsLabel: "Explore specs",
    enforcementGatewayPortalLabel: "Enforcement Gateway Portal",
    activePortLabel: "Active (Port: 3000)",
    resetSecurityLockBtn: "Reset Security Lock",
    sandboxEmailLogsTitle: "Sandbox Email logs",
    loggedToLabel: "logged to",
    inboxEmptyTitle: "Inbox empty",
    inboxEmptyDesc: "Trigger standard validation from the French option, and security keys will appear instantly.",
    byLabel: "By",
    filledLabel: "Filled",
    autofillLabel: "Autofill",
    previewEmailPrompt: "Choose an OTP mail from the list to preview security token code.",
  },
  [LanguageCode.ES]: {
    metaTitle: "Portal Global",
    heroBadge: "Centro seguro de varios idiomas",
    heroTitle: "Desbloquee el potencial global",
    heroSub: "Interactúe a la perfección con nuestra plataforma localizada en el idioma que prefiera. La validación segura protege los accesos premium.",
    featuresTitle: "Capacidades empresariales",
    featuresDesc: "Explore las características diseñadas para operaciones multinacionales y sistemas de seguridad robustos.",
    serviceTitle: "Servicios Globales",
    serviceDesc: "Unidades de negocios digitales de alta calidad con compatibilidad integrada para múltiples lenguas.",
    profileTitle: "Bóveda de Seguridad",
    profileDesc: "Revise sus credenciales seguras y el estado de su autorización de idioma para un control validado.",
    
    analyticsCardTitle: "Analítica Global",
    analyticsCardDesc: "Agregación de tráfico en tiempo real de más de 140 países con sincronización absoluta.",
    marketCardTitle: "Traductor de Núcleo Neural",
    marketCardDesc: "Aproveche los modelos avanzados de Gemini en el servidor para traducir anuncios personalizados de forma dinámica.",
    supportCardTitle: "Protocolo de Seguridad",
    supportCardDesc: "La verificación de OTP de múltiples factores protege las regiones francófonas.",
    
    service1Name: "API de Localización Dinámica",
    service1Desc: "Difunda estados de traducción instantáneos a marcos de aplicaciones e interfaces distribuidas.",
    service2Name: "Bróker de Verificación de Identidad",
    service2Desc: "Autentica usuarios mediante generación de códigos temporales de seguridad antes de habilitar idiomas restringidos.",
    service3Name: "Motor de Recursos Localizados",
    service3Desc: "Proporciona contenido multimedia, tipografía y formatos numéricos que responden a las preferencias locales.",
    
    accountEmailLabel: "Verificación de Cuenta Registrada",
    registeredEmail: "",
    securityVerificationStatus: "Nivel de privilegio de segurança",
    verifiedLabel: "Totalmente Verificado (Acceso Activo)",
    verificationRequiredLabel: "Requiere OTP para Francés",
    languageLockDisclaimer: "Aviso: El idioma francés requiere una verificación única de OTP enviada a su correo para validar las pautas de acceso específicas de la región.",
    
    navHome: "Inicio",
    navServices: "Servicios",
    navSecurity: "Seguridad",
    changeLanguageBtn: "Cambiar idioma",
    generateOtpBtn: "Generar OTP de forma segura",
    sendingLabel: "Generando...",
    sentLabel: "Revisar bandeja de entrada",
    verifyAndApplyBtn: "Verificar y aplicar cambios",
    enterOtpPlaceholder: "Ingrese el código OTP de 6 dígitos",
    invalidOtpError: "Código incorrecto: El código de verificación solicitado no es válido o ha expirado.",
    otpVerifiedSuccess: "¡Éxito! La autorización para el idioma francés ha sido activada.",
    frenchLockedBadge: "Acceso Protegido por Seguridad",
    generalSuccess: "Las traducciones se han aplicado con éxito.",

    // New Localized Elements
    tabDashboard: "Tablero",
    tabAssets: "Recursos",
    tabPreferences: "Preferencias",
    tabSecurity: "Seguridad",
    langSettingsTitle: "Ajustes de Idioma",
    langSettingsDesc: "Elija su idioma de interfaz preferido. Los cambios se aplican globalmente en todos los módulos.",
    securityVerificationTitle: "Verificación de Seguridad",
    securityVerificationdesc: "Cambiar a francés requiere validación de correo electrónico para esta región. Por favor verifique su identidad.",
    registeredEmailLabel: "Correo Registrado",
    generateOtpCodeBtn: "Generar Código OTP",
    generatingCodeLabel: "Generando código...",
    codeSentAlert: "¡Se ha enviado con éxito un código de verificación de 6 dígitos!",
    verifyAndApplyLanguageBtn: "Verificar y Aplicar Idioma",
    invalidOtpFormatError: "Por favor ingrese un código de verificación de 6 dígitos válido.",
    authProxyOfflineError: "Servidor de autenticación sin conexión. Inténtelo de nuevo.",
    waitResendLabel: "Espere {time}s para reenviar el código",
    readyResendLabel: "Listo para reenviar el código",
    enterpriseDashboardTitle: "Descripción General del Tablero Corporativo",
    enterpriseDashboardDesc: "Explore métricas visuales premium y estados de API integrados.",
    dynamicNeuralTitle: "Localizador Neural Dinámico (Impulsado por Gemini)",
    activeLocaleLabel: "CONFIGURACIÓN REGIONAL ACTIVA",
    translatorHintDesc: "Pruebe la velocidad de localización real respaldada por las API de IA de Gemini 3.5: Escriba cualquier texto o frase, y al hacer clic en traducir se localizará sin problemas en el diccionario seleccionado activo.",
    sourceTextLabel: "Copia de origen (Inglés)",
    textareaPlaceholderText: "Ingrese texto para probar la localización...",
    translatedTargetLabel: "Objetivo Traducido",
    streamingConversionLabel: "Transmisión de conversión neural dinámica...",
    noConvertedOutputLabel: "Aún no hay salida traducida. Ingrese texto y ejecute el traductor.",
    triggerDynamicTranslationBtn: "Iniciar Traducción Dinámica",
    exploreSpecsLabel: "Explorar especificaciones",
    enforcementGatewayPortalLabel: "Portal de Pasarela de Aplicación",
    activePortLabel: "Activo (Puerto: 3000)",
    resetSecurityLockBtn: "Restablecer Bloqueo de Seguridad",
    sandboxEmailLogsTitle: "Registros de correo de Sandbox",
    loggedToLabel: "conectado a",
    inboxEmptyTitle: "Bandeja de entrada vacía",
    inboxEmptyDesc: "Active la validación estándar desde la opción de francés y las claves de seguridad aparecerán al instante.",
    byLabel: "Por",
    filledLabel: "Llenado",
    autofillLabel: "Autollenar",
    previewEmailPrompt: "Elija un correo OTP de la lista para ver el código del token de seguridad.",
  },
  [LanguageCode.HI]: {
    metaTitle: "वैश्विक पोर्टल",
    heroBadge: "सुरक्षित बहु-भाषा केंद्र",
    heroTitle: "वैश्विक क्षमता को अनलॉक करें",
    heroSub: "अपनी पसंद की स्थानीयकृत भाषा में हमारे वैश्विक मंच के साथ निर्बाध रूप से बातचीत करें। सुरक्षित सत्यापन प्रीमियम रास्तों की रक्षा करता है।",
    featuresTitle: "उद्यम क्षमताएं",
    featuresDesc: "मजबूत बहुराष्ट्रीय संचालन और सुरक्षित प्राधिकरण प्रणालियों के लिए डिज़ाइन की गई शीर्ष सुविधाओं का अन्वेषण करें।",
    serviceTitle: "हमारी वैश्विक सेवाएं",
    serviceDesc: "एकीकृत राज्य दृढ़ता के साथ कई भाषाओं की सेवा करने वाली उच्च श्रेणी की डिजिटल व्यवसाय इकाइयाँ।",
    profileTitle: "सुरक्षा तिजोरी",
    profileDesc: "सत्यापित पहुंच नियंत्रण के लिए अपने सुरक्षित क्रेडेंशियल और भाषा मंजूरी की स्थिति की समीक्षा करें।",
    
    analyticsCardTitle: "वैश्विक विश्लेषिकी",
    analyticsCardDesc: "पूर्ण सिंक्रनाइज़ेशन के साथ 140 से अधिक देशों का प्रतिनिधित्व करने वाला रीयल-टाइम ट्रैफ़िक एकीकरण।",
    marketCardTitle: "न्यूरल कोर अनुवादक",
    marketCardDesc: "किसी भी कस्टम घोषणा का गतिशील रूप से अनुवाद करने के लिए सर्वर पर उन्नत जेमिनी मॉडल का उपयोग करें।",
    supportCardTitle: "सुरक्षित प्रोटोकॉल",
    supportCardDesc: "बहु-कारक ओटीपी सत्यापन उच्च-अनुपालन वाले क्षेत्रों की सुरक्षा करता है, जिसमें फ्रांसीसी क्षेत्र भी शामिल हैं।",
    
    service1Name: "गतिशील स्थानीयकरण एपीआई",
    service1Desc: "कई क्षेत्रों में वितरित एप्लिकेशन फ़्रेमों में शब्दकोश राज्यों का तुरंत प्रचार करें।",
    service2Name: "पहचान सत्यापन ब्रोकर",
    service2Desc: "स्थानीयकृत सेटिंग्स को अनुमति देने से पहले मानक टोकन के माध्यम से उपयोगकर्ताओं को प्रमाणित करता है।",
    service3Name: "स्थानीयकृत संपत्ति इंजन",
    service3Desc: "मूल लक्ष्य प्राथमिकताओं के अनुरूप विशेष मल्टीमीडिया सामग्री, फ़ॉन्ट और संख्यात्मक प्रारूप प्रदान करता है।",
    
    accountEmailLabel: "पंजीकृत खाता सत्यापन",
    registeredEmail: "",
    securityVerificationStatus: "सुरक्षा सत्यापन विशेषाधिकार स्तर",
    verifiedLabel: "पूरी तरह से सत्यापित (मंजूरी सक्रिय)",
    verificationRequiredLabel: "फ्रेंच भाषाओं के लिए ओटीपी जांच आवश्यक है",
    languageLockDisclaimer: "सूचना: स्थानीय-विशिष्ट पहुंच दिशानिर्देशों को सत्यापित करने के लिए फ्रेंच भाषा के लिए आपके ईमेल पर भेजे गए एक-बार सुरक्षित ओटीपी की आवश्यकता होती है।",
    
    navHome: "मुख्य पोर्टल",
    navServices: "सेवाएं",
    navSecurity: "सुरक्षा",
    changeLanguageBtn: "भाषा बदलें",
    generateOtpBtn: "सुरक्षित ओटीपी जनरेट करें",
    sendingLabel: "जनरेट हो रहा है...",
    sentLabel: "इनबॉक्स देखें",
    verifyAndApplyBtn: "सत्यापित करें और लागू करें",
    enterOtpPlaceholder: "6-अंकीय सत्यापन ओटीपी दर्ज करें",
    invalidOtpError: "पहुंच अस्वीकृत: अनुरोधित सत्यापन कोड अमान्य है या समाप्त हो गया है।",
    otpVerifiedSuccess: "सफलता! फ्रेंच भाषा की अनुमति सफलतापूर्वक अधिकृत कर दी गई है।",
    frenchLockedBadge: "सुरक्षा मंजूरी कवच",
    generalSuccess: "वेबसाइट सामग्री अनुवाद सफलतापूर्वक लागू किए गए।",

    // New Localized Elements
    tabDashboard: "डैशबोर्ड",
    tabAssets: "संपत्तियां",
    tabPreferences: "प्राथमिकताएं",
    tabSecurity: "सुरक्षा",
    langSettingsTitle: "भाषा सेटिंग्स",
    langSettingsDesc: "अपनी पसंदीदा इंटरफ़ेस भाषा चुनें। परिवर्तन सभी मॉड्यूल में विश्व स्तर पर लागू होते हैं।",
    securityVerificationTitle: "सुरक्षा सत्यापन",
    securityVerificationdesc: "फ़्रेंच में स्विच करने के लिए इस क्षेत्र के लिए ईमेल सत्यापन की आवश्यकता है। कृपया अपनी पहचान सत्यापित करें।",
    registeredEmailLabel: "पंजीकृत ईमेल",
    generateOtpCodeBtn: "ओटीपी कोड जनरेट करें",
    generatingCodeLabel: "कोड जनरेट हो रहा है...",
    codeSentAlert: "6-अंकीय सत्यापन कोड सफलतापूर्वक भेज दिया गया है!",
    verifyAndApplyLanguageBtn: "सत्यापित करें और भाषा लागू करें",
    invalidOtpFormatError: "कृपया एक वैध 6-अंकीय सत्यापन कोड प्रदान करें।",
    authProxyOfflineError: "ऑथ प्रॉक्सी ऑफ़लाइन है। फिर प्रयास करें।",
    waitResendLabel: "कोड दोबारा भेजने के लिए {time}s प्रतीक्षा करें",
    readyResendLabel: "कोड दोबारा भेजने के लिए तैयार",
    enterpriseDashboardTitle: "एंटरप्राइज डैशबोर्ड अवलोकन",
    enterpriseDashboardDesc: "प्रीमियम दृश्य मेट्रिक्स और एकीकृत एपीआई स्थिति का पता लगाएं।",
    dynamicNeuralTitle: "गतिशील तंत्रिका स्थानीयकरण (जेमिनी द्वारा संचालित)",
    activeLocaleLabel: "सक्रिय भाषा",
    translatorHintDesc: "जेमिनी 3.5 एआई एपीआई द्वारा समर्थित वास्तविक स्थानीयकरण गति का परीक्षण करें: कोई भी पाठ या वाक्यांश टाइप करें, और अनुवाद पर क्लिक करने से यह वर्तमान चयनित सक्रिय भाषा शब्दकोश में सहजता से स्थानीयकृत हो जाएगा।",
    sourceTextLabel: "स्रोत प्रति (अंग्रेजी)",
    textareaPlaceholderText: "स्थानीयकरण का परीक्षण करने के लिए पाठ दर्ज करें...",
    translatedTargetLabel: "अनुवादित लक्ष्य",
    streamingConversionLabel: "गतिशील तंत्रिका रूपांतरण स्ट्रीमिंग...",
    noConvertedOutputLabel: "अभी तक कोई अनुवादित आउटपुट नहीं है। पाठ दर्ज करें और अनुवादक चलाएं।",
    triggerDynamicTranslationBtn: "गतिशील अनुवाद ट्रिगर करें",
    exploreSpecsLabel: "विवरण देखें",
    enforcementGatewayPortalLabel: "प्रवर्तन गेटवे पोर्टल",
    activePortLabel: "सक्रिय (पोर्ट: 3000)",
    resetSecurityLockBtn: "सुरक्षा लॉक रीसेट करें",
    sandboxEmailLogsTitle: "सैंडबॉक्स ईमेल लॉग",
    loggedToLabel: "लॉग इन",
    inboxEmptyTitle: "इनबॉक्स खाली है",
    inboxEmptyDesc: "फ़्रेंच विकल्प से मानक सत्यापन ट्रिगर करें, और सुरक्षा कोड तुरंत दिखाई देंगे।",
    byLabel: "द्वारा",
    filledLabel: "भरा गया",
    autofillLabel: "स्वतः भरें",
    previewEmailPrompt: "सुरक्षा टोकन कोड का पूर्वावलोकन करने के लिए सूची से एक ओटीपी ईमेल चुनें।",
  },
  [LanguageCode.PT]: {
    metaTitle: "Portal Global",
    heroBadge: "Hub Seguro Multi-Idioma",
    heroTitle: "Desbloqueie o Potencial Global",
    heroSub: "Interaja perfeitamente com nossa plataforma global localizada no idioma de sua escolha. A validação segura protege o acesso premium.",
    featuresTitle: "Recursos Corporativos",
    featuresDesc: "Explore os principais recursos projetados para robustas operações multinacionais e sistemas de autorização seguros.",
    serviceTitle: "Nossos Serviços Globais",
    serviceDesc: "Unidades de negócios digitais de alto nível que atendem a múltiplos idiomas com persistência unificada de dados.",
    profileTitle: "Cofre de Segurança",
    profileDesc: "Revise suas credenciais de segurança e o status de aprovação de idioma para controle de acesso validado.",
    
    analyticsCardTitle: "Análises Globais",
    analyticsCardDesc: "Agregação de tráfego em tempo real representando mais de 140 países com sincronização absoluta.",
    marketCardTitle: "Tradutor de Núcleo Neural",
    marketCardDesc: "Aproveite modelos avançados da Gemini no servidor para traduzir dinamicamente quaisquer anúncios personalizados.",
    supportCardTitle: "Protocolo de Segurança",
    supportCardDesc: "A verificação OTP de múltiplos fatores protege locais de alta conformidade, incluindo regiões francófonas.",
    
    service1Name: "API de Localização Dinâmica",
    service1Desc: "Propague instantaneamente estados do dicionário para quadros de aplicativos distribuídos em várias regiões.",
    service2Name: "Corretor de Verificação de Identidade",
    service2Desc: "Autentica usuários via geração de tokens padrão antes de conceder acesso a configurações localizadas.",
    service3Name: "Motor de Ativos Localizados",
    service3Desc: "Fornece conteúdo multimídia sob medida, fontes e formatos numéricos que atendem às preferências nativas.",
    
    accountEmailLabel: "Verificação da Conta Registrada",
    registeredEmail: "",
    securityVerificationStatus: "Nível de privilégio de segurança",
    verifiedLabel: "Totalmente Verificado (Liberação Ativa)",
    verificationRequiredLabel: "Verificação de OTP para Francês Necessária",
    languageLockDisclaimer: "Aviso: O idoma francês requer uma verificação única de OTP enviada para o seu e-mail para validar as diretrizes de acesso da região.",
    
    navHome: "Início",
    navServices: "Serviços",
    navSecurity: "Segurança",
    changeLanguageBtn: "Alterar Idioma",
    generateOtpBtn: "Gerar OTP com Segurança",
    sendingLabel: "Gerando...",
    sentLabel: "Verificar Entrada",
    verifyAndApplyBtn: "Verificar e Aplicar",
    enterOtpPlaceholder: "Insira o código OTP de 6 dígitos",
    invalidOtpError: "Acesso Negado: O código de verificação solicitado é inválido ou expirou.",
    otpVerifiedSuccess: "Sucesso! A permissão para o idioma francês foi autorizada com êxito.",
    frenchLockedBadge: "Escudo de Segurança Ativo",
    generalSuccess: "As traduções de conteúdo do site foram aplicadas com sucesso.",

    // New Localized Elements
    tabDashboard: "Painel",
    tabAssets: "Ativos",
    tabPreferences: "Preferências",
    tabSecurity: "Segurança",
    langSettingsTitle: "Configurações de Idioma",
    langSettingsDesc: "Escolha o seu idioma de interface preferido. As alterações são aplicadas globalmente em todos os módulos.",
    securityVerificationTitle: "Verificação de Segurança",
    securityVerificationdesc: "A mudança para o francês requer validação de e-mail para esta região. Por favor, verifique a sua identidade.",
    registeredEmailLabel: "E-mail Registrado",
    generateOtpCodeBtn: "Gerar Código OTP",
    generatingCodeLabel: "Gerando código...",
    codeSentAlert: "Um código de verificação de 6 dígitos foi enviado com sucesso!",
    verifyAndApplyLanguageBtn: "Verificar e Aplicar Idioma",
    invalidOtpFormatError: "Por favor, forneça um código de verificação válido de 6 dígitos.",
    authProxyOfflineError: "Servidor de autenticação offline. Tente novamente.",
    waitResendLabel: "Aguarde {time}s para reenviar o código",
    readyResendLabel: "Pronto para reenviar o código",
    enterpriseDashboardTitle: "Visão Geral do Painel Corporativo",
    enterpriseDashboardDesc: "Explore métricas visuais premium e status de APIs integradas.",
    dynamicNeuralTitle: "Localizador Neural Dinâmico (Alimentado por Gemini)",
    activeLocaleLabel: "IDIOMA ATIVO",
    translatorHintDesc: "Teste a velocidade de localização real apoiada pelas APIs da Gemini 3.5 AI: Digite qualquer texto ou frase, e clicar em traduzir irá localizá-lo perfeitamente no dicionário selecionado ativo.",
    sourceTextLabel: "Cópia de origem (Inglês)",
    textareaPlaceholderText: "Digite o texto para testar a localização...",
    translatedTargetLabel: "Alvo Traduzido",
    streamingConversionLabel: "Transmissão da conversão neural dinâmica...",
    noConvertedOutputLabel: "Ainda não há saída traduzida. Digite o texto e execute o tradutor.",
    triggerDynamicTranslationBtn: "Disparar Tradução Dinâmica",
    exploreSpecsLabel: "Explorar especificações",
    enforcementGatewayPortalLabel: "Portal de Gateway de Aplicação",
    activePortLabel: "Ativo (Porta: 3000)",
    resetSecurityLockBtn: "Redefinir Bloqueio de Segurança",
    sandboxEmailLogsTitle: "Registros de E-mail da Sandbox",
    loggedToLabel: "conectado a",
    inboxEmptyTitle: "Caixa de entrada vazia",
    inboxEmptyDesc: "Acione a validação padrão a partir da opção francesa e as chaves de segurança aparecerão instantaneamente.",
    byLabel: "Por",
    filledLabel: "Preenchido",
    autofillLabel: "Preenchimento Automático",
    previewEmailPrompt: "Escolha um e-mail OTP da lista para visualizar o código do token de segurança.",
  },
  [LanguageCode.ZH]: {
    metaTitle: "全球门户",
    heroBadge: "安全多语言中心",
    heroTitle: "释放全球潜能",
    heroSub: "轻松体验您所选语言的本地化全球平台。全面的安全验证守护高端应用通道。",
    featuresTitle: "企业级高能架构",
    featuresDesc: "探索专门面向跨国业务及高敏感安全验证系统打造的顶级性能指标。",
    serviceTitle: "我们的全球服务",
    serviceDesc: "支持多语种统一状态持久化的高级数字化商业应用组件。",
    profileTitle: "安全隔离舱",
    profileDesc: "审查您的账号安全凭证与目标语言的准入鉴权状态。",
    
    analyticsCardTitle: "全球数据透视",
    analyticsCardDesc: "代表超140个国家与地区的实时流量汇聚，实施绝对的时序同步。",
    marketCardTitle: "神经中枢翻译器",
    marketCardDesc: "利用服务端的 Gemini 高级大语言模型，实时、动态地翻译您的任何个性化通告。",
    supportCardTitle: "高强度合规协议",
    supportCardDesc: "通过多因子 OTP 安全密钥，为主流法语区及高合规审计地域提供鉴权盾牌。",
    
    service1Name: "动态本地化接口 API",
    service1Desc: "瞬间在分布式应用实例中广播共享最新的翻译词条与文案包。",
    service2Name: "身份真伪校验调度器",
    service2Desc: "在放行受限语言选项前，统一执行符合行业标准的单次邮件验证码安全甄别。",
    service3Name: "国家化静态资源引擎",
    service3Desc: "分发专为本土习惯优化的音视频、排版字体以及数值度量衡格式。",
    
    accountEmailLabel: "已注册账户的安全鉴权",
    registeredEmail: "",
    securityVerificationStatus: "安全级别许可特权",
    verifiedLabel: "尊享全功能访问 (鉴权白名单激活)",
    verificationRequiredLabel: "法语选定需要进行 OTP 安全验证",
    languageLockDisclaimer: "注意：启用法语需要对您的注册邮箱发起一次性 OTP 安全密钥验证，以证明您对特定法语区数据的安全合规许可。",
    
    navHome: "首页面板",
    navServices: "服务总线",
    navSecurity: "安全中心",
    changeLanguageBtn: "选择当前语言",
    generateOtpBtn: "启动 OTP 安全验证码生成",
    sendingLabel: "正在请求发送...",
    sentLabel: "请查看收件箱",
    verifyAndApplyBtn: "校验检验码并保存设置",
    enterOtpPlaceholder: "请输入6位验证码",
    invalidOtpError: "验证失败：您输入的验证码无效或已过期，请重新获取。",
    otpVerifiedSuccess: "验证通过！法语语言准入规则已获准授予。",
    frenchLockedBadge: "高级安全围栏拦截",
    generalSuccess: "当前语言资源包更新成功。",

    // New Localized Elements
    tabDashboard: "仪表盘",
    tabAssets: "数字资产",
    tabPreferences: "语言首选项",
    tabSecurity: "安全中心",
    langSettingsTitle: "语言设置",
    langSettingsDesc: "选择您的首选界面语言，修改将全局应用到所有模块。",
    securityVerificationTitle: "安全验证",
    securityVerificationdesc: "切换为法语需要此区域进行邮箱验证。请核验您的身份。",
    registeredEmailLabel: "已注册的电子邮箱",
    generateOtpCodeBtn: "生成 OTP 安全验证码",
    generatingCodeLabel: "正在生成验证码...",
    codeSentAlert: "6位安全验证码已成功发送！",
    verifyAndApplyLanguageBtn: "验证并应用语言",
    invalidOtpFormatError: "请输入正确的6位验证码。",
    authProxyOfflineError: "身份验证代理离线，请重试。",
    waitResendLabel: "请等待 {time} 秒后重试",
    readyResendLabel: "可重新获取验证码",
    enterpriseDashboardTitle: "企业级仪表盘一览",
    enterpriseDashboardDesc: "快速了解高阶视觉体验及关联的 API 服务运行状态。",
    dynamicNeuralTitle: "动态神经网络翻译器 (基于 Gemini 驱使)",
    activeLocaleLabel: "当前语言环境",
    translatorHintDesc: "测试基于 Gemini 3.5 智能接口的实时翻译转换：在左侧输入任何句式，转化键将瞬间按选定的共享字典包将其更新。",
    sourceTextLabel: "英语源头文案",
    textareaPlaceholderText: "请输入需要检测的本地化文案...",
    translatedTargetLabel: "本地输出目标",
    streamingConversionLabel: "神经网络引擎正在响应转换...",
    noConvertedOutputLabel: "尚无匹配的本地化产出。请在左侧键入内容并触发转换。",
    triggerDynamicTranslationBtn: "立即启动文本转换",
    exploreSpecsLabel: "查看技术规范",
    enforcementGatewayPortalLabel: "安全合规通道入口",
    activePortLabel: "活跃状态 (服务端口: 3000)",
    resetSecurityLockBtn: "重置安全锁定标识",
    sandboxEmailLogsTitle: "沙盒模拟邮件接收器",
    loggedToLabel: "绑定宿主",
    inboxEmptyTitle: "邮件收件箱为空",
    inboxEmptyDesc: "从语言栏选择法语选项并触发核验发送，安全验证码邮件瞬间即会呈现在当前区域。",
    byLabel: "发送方",
    filledLabel: "已填充",
    autofillLabel: "自动录入",
    previewEmailPrompt: "从左侧列表点选一封邮件以在右下侧阅读完整的安全令牌明文。",
  },
  [LanguageCode.FR]: {
    metaTitle: "Portail Global",
    heroBadge: "Hub Multi-Langues Sécurisé",
    heroTitle: "Libérez le Potentiel Global",
    heroSub: "Interagissez de manière transparente avec notre plateforme globale localisée dans la langue de votre choix. La validation stricte assure un accès premium.",
    featuresTitle: "Capacités d'Entreprise",
    featuresDesc: "Explorez des fonctionnalités pensées pour les opérations multinationales et des systèmes d'autorisation robustes.",
    serviceTitle: "Nos Services Globaux",
    serviceDesc: "Unités commerciales numériques de haute qualité fournissant une persistance de session unifiée multi-langues.",
    profileTitle: "Coffre-Fort de Sécurité",
    profileDesc: "Consultez vos identifiants sécurisés et votre niveau d'accréditation linguistique pour un contrôle optimal.",
    
    analyticsCardTitle: "Analyses Globales",
    analyticsCardDesc: "Agrégation de trafic en temps réel représentant plus de 140 pays avec une synchronisation absolue.",
    marketCardTitle: "Traducteur de Noyau Neural",
    marketCardDesc: "Exploitez les modèles avancés Gemini côté serveur pour traduire dynamiquement vos annonces d'entreprise.",
    supportCardTitle: "Protocole Sécurisé",
    supportCardDesc: "La validation OTP par emails protège les accès aux portails restrictifs comme les instances francophones.",
    
    service1Name: "API de Localisation Dynamique",
    service1Desc: "Propaguez instantanément les dictionnaires traduits à l'ensemble des cadres d'applications distribués.",
    service2Name: "Courtier d'Identité Sécurisé",
    service2Desc: "Authentifie les profils via l'émission de codes à usage unique avant d'activer les préférences linguistiques sensibles.",
    service3Name: "Moteur de Contenus Spécifiques",
    service3Desc: "Distribue les médias, typographies et représentations de valeurs numériques en accord avec la région d'usage.",
    
    accountEmailLabel: "Validation du Compte Enregistré",
    registeredEmail: "",
    securityVerificationStatus: "Niveau d'accréditation de sécurité",
    verifiedLabel: "Entièrement Vérifié (Accès Totalement Validé)",
    verificationRequiredLabel: "Contrôle OTP Requis pour la Langue Française",
    languageLockDisclaimer: "Avis : L'activation de l'environnement français nécessite un contrôle de sécurité par OTP, envoyé à votre email, afin de certifier les droits d'accès régionaux.",
    
    navHome: "Portail d'Accueil",
    navServices: "Pôle Services",
    navSecurity: "Sécurité & Profil",
    changeLanguageBtn: "Changer de langue",
    generateOtpBtn: "Générer un OTP Sécurisé",
    sendingLabel: "Génération...",
    sentLabel: "Consultez vos messages",
    verifyAndApplyBtn: "Valider l'OTP & Mettre à jour",
    enterOtpPlaceholder: "Saisir le code OTP à 6 chiffres",
    invalidOtpError: "Accès Refusé : Le jeton de sécurité fourni est invalide ou a expiré.",
    otpVerifiedSuccess: "Succès ! Vos droits pour la langue française ont été formellement validés.",
    frenchLockedBadge: "Périmètre Sécurisé Shieldé",
    generalSuccess: "Les traductions de la plateforme ont été appliquées avec succès.",

    // New Localized Elements
    tabDashboard: "Tableau de bord",
    tabAssets: "Actifs",
    tabPreferences: "Préférences",
    tabSecurity: "Sécurité",
    langSettingsTitle: "Paramètres de langue",
    langSettingsDesc: "Choisissez votre langue d'interface préférée. Les modifications s'appliquent globalement à tous les modules.",
    securityVerificationTitle: "Vérification de Sécurité",
    securityVerificationdesc: "Le passage au français nécessite une validation de courriel pour cette région. Veuillez vérifier votre identité.",
    registeredEmailLabel: "Courriel Enregistré",
    generateOtpCodeBtn: "Générer le Code OTP",
    generatingCodeLabel: "Génération du code...",
    codeSentAlert: "Un code de vérification à 6 chiffres a été envoyé avec succès !",
    verifyAndApplyLanguageBtn: "Vérifier & Appliquer la Langue",
    invalidOtpFormatError: "Veuillez fournir un code de vérification valide à 6 chiffres.",
    authProxyOfflineError: "Serveur d'authentification hors ligne. Réessayez.",
    waitResendLabel: "Attendez {time}s pour renvoyer le code",
    readyResendLabel: "Prêt à renvoyer le code",
    enterpriseDashboardTitle: "Aperçu du Tableau de Bord d'Entreprise",
    enterpriseDashboardDesc: "Explorez des indicateurs visuels haut de gamme et les statuts d'API intégrés.",
    dynamicNeuralTitle: "Localisateur Neural Dynamique (Propulsé par Gemini)",
    activeLocaleLabel: "PARAMÈTRE RÉGIONAL ACTIF",
    translatorHintDesc: "Testez la vitesse de localisation réelle soutenue par les API d'IA Gemini 3.5 : Saisissez n'importe quel texte ou phrase, et cliquez sur traduire pour le localiser de façon transparente dans le dictionnaire actif sélectionné.",
    sourceTextLabel: "Copie source (Anglais)",
    textareaPlaceholderText: "Saisissez du texte pour tester la localisation...",
    translatedTargetLabel: "Cible Traduite",
    streamingConversionLabel: "Conversion neurale dynamique en cours...",
    noConvertedOutputLabel: "Pas encore de résultat traduit. Entrez du texte et lancez le traducteur.",
    triggerDynamicTranslationBtn: "Lancer la Traduction Dynamique",
    exploreSpecsLabel: "Explorer les spécifications",
    enforcementGatewayPortalLabel: "Portail de Passerelle d'Application",
    activePortLabel: "Actif (Port: 3000)",
    resetSecurityLockBtn: "Réinitialiser le Verrou de Sécurité",
    sandboxEmailLogsTitle: "Journaux de Courriels Sandbox",
    loggedToLabel: "connecté à",
    inboxEmptyTitle: "Boîte de réception vide",
    inboxEmptyDesc: "Déclenchez la validation standard depuis l'option française et les clés de sécurité s'afficheront instantanément.",
    byLabel: "Par",
    filledLabel: "Rempli",
    autofillLabel: "Remplissage auto",
    previewEmailPrompt: "Choisissez un courriel OTP dans la liste pour prévisualiser le code du jeton de sécurité.",
  }
};
